### ISSUE TITLE
Write (unit)tests to improve code coverage

### ISSUE THREAD

**Issue by NoraHagmeyer** [imcs-compsim/MIRCO#22]
## Description
Every line of code that is not tested has the potential of bugs. Tests should be introduced for every line of the code.

## Possible Solution and Definition of Done

- [x] LinearSolver
- [x] NonlinearSolver
- ~Evaluate~
- [x] Warmstart
- [x] RMD Generator
- ~Read Topology from file~
- ~WriteForce~
- [x] SetupParameter

## Related Issues and Merge Requests

* Blocks
* Is blocked by
* Follows
* Precedes
* Related to
* Part of
* Composed of

**Comment by RShaw026** [comment]
I looked into the possibility of writing more unit tests but could not find one. We are not going to test the Input-Output functions as unit tests. Framework testing would be sufficient for testing the "Evaluate" function. #43 addresses this issue with PR #91.

Closing this issue.
