### ISSUE TITLE
Simulation should not write output into source Input directory

### ISSUE THREAD

**Issue by mayrmt** [imcs-compsim/MIRCO#36]
## Description

When running `./mirco <sourceDir>/Input/input_sup2.xml`, then a file `<sourceDir>/Input/result_force_sup2.dat` is created. In order to clearly separate source and build directory as well as input and output, but mainly to keep the source directory clean and avoid accidental committing of result files, a simulation may not write its output into the source directory. I'd be ok to write output to the build directory.

## Possible Solution and Definition of Done

- [ ] Change path of simulation output files
- [ ] Maybe: do not even read the input files from the source directory directly, buy copy them via some CMake commands from the source to the build directory during the build stage. Then, read input from the build directory. This greatly decouples source and build directory, although one needs to "recompile" in order to get changes from the input files in the source directory synced to the build directory.

## Interested Parties
@RShaw026 @NoraHagmeyer @tsarikahin

**Comment by RShaw026** [comment]
The simulation no longer writes output into the source input directory. Currently, it just prints the output pressure in the console. The proper input-output relationship will be discussed in #14 . Closing this issue
