### ISSUE TITLE
Make repository public

### ISSUE THREAD

**Issue by NoraHagmeyer** [imcs-compsim/MIRCO#54]
To increase visibility and to enable at least read access for all baci contributors, we decided to make this repo open-source, at least once it has been sucessfully integrated into baci as an optional external library. To still keep this repo and all our test runners safe, there is still some work to be done.

## Possible Solution and Definition of Done
- [x] Restrict privileges to run workflows only to members (of our organization)
- [ ] Think of other important steps 
   - [x] Add info on how to cite this code 
   - [x] Provide a `CONTRIBUTING.md` document
   - [x] Explicitly state external dependencies (such as Trilinos)
   - [ ] _(optional)_ Trilinos: check for required packages
- [x] make repo public

## Additional Information
See for example this blog for additional information on safety concerns https://blog.gitguardian.com/github-actions-security-cheat-sheet/

## Interested Parties
@mayrmt

**Comment by mayrmt** [comment]
I just have published the repository. This completes this issue. Let's open another one, if we encounter any problems.

**Comment by eulovi** [comment]
As @NoraHagmeyer mentioned before, we have to set the options to give approval for workflows ran by external contributors. According to [this](https://blog.gitguardian.com/github-actions-security-cheat-sheet/), we have to change the settings following [these instructions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories) and select **Require approval for all outside collaborators**. @mayrmt, can you apply those changes?

**Comment by mayrmt** [comment]
@eulovi I have change the settings as outlined.

**Comment by NoraHagmeyer** [comment]
> As @NoraHagmeyer mentioned before, we have to set the options to give approval for workflows ran by external contributors. According to [this](https://blog.gitguardian.com/github-actions-security-cheat-sheet/), we have to change the settings following [these instructions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories) and select **Require approval for all outside collaborators**. @mayrmt, can you apply those changes?

@eulovi Done! We also protected the master, which was apparently not done before, and we now require at least 1 approval for pull requests.
