### ISSUE TITLE
Trilinos target not defined

### ISSUE THREAD

**Issue by maxfirmbach** [imcs-compsim/MIRCO#82]
## Expectations

In line 129 of `CMakeLists.txt` the target `_Trilinos_all_selected_libs` is used. This can cause issues, as the target might not be defined to this point depending what happens in the file before (see `if` in line 28).

## Possible Solution

Use a different target, does `Trilinos::all_selected_libs` do the job?

## Your Environment

- **Relevant repo SHA1s:**
- **Relevant configure flags or configure script:**
- **Operating system and version:**
- **Compiler and TPL versions:**

## Related Issues and Merge Requests

* Blocks
* Follows
* Related to
* Part of
* Composed of

## Interested Parties

@mayrmt @NoraHagmeyer @RShaw026 @eulovi

**Comment by maxfirmbach** [comment]
Do you even need that target at that place?

**Comment by RShaw026** [comment]
@maxfirmbach To create an export in line 129, I can't use `Trilinos::all_selected_libs` . So instead, I can create an INTERFACE target called `_Trilinos_all_selected_libs` in line 47 and link `Trilinos::all_selected_libs` to it. I have these changes in a branch now. Trying to build that with BACI in the pipeline now.
